#!/bin/bash
set -euo pipefail

sd 'rev:.*' "rev: $(git rev-parse --short HEAD)" index.html
if [[ $(uname) =~ Linux ]]; then xhost + &>/dev/null; fi
npx electron-pdf -b true $(pwd)/index.html $(pwd)/cv.pdf
