#!/bin/bash
set -euxo pipefail

BUILD_DIR="../docs/cv"
mkdir -p "$BUILD_DIR"

erb index.html.erb > "$BUILD_DIR/index.html"
npx electron-pdf -b true "$(pwd)/$BUILD_DIR/index.html" "$(pwd)/$BUILD_DIR/cv.pdf"
node first_page.js "$BUILD_DIR/cv.pdf"

# Copy assets
cp -r assets "$BUILD_DIR/"
cp style.css "$BUILD_DIR/"
